### ISSUE TITLE
Wording might need changes

### ISSUE THREAD

**Issue by raq929** [ga-wdi-boston/ruby-objects-self#17]
So, the first part of this repo says: `For example, let's say we have a model named Person that inherits from ActiveRecord::Base`

But in the code (`person.rb`), our Person model does not inherit from ActiveRecord, and unless I'm mistaken, we're not doing anything with Rails yet, so it doesn't make much sense to talk about ActiveRecord. 
Is it OK to take this out, or am I missing something?

**Comment by payne-chris-r** [comment]
Good catch. I think it's probably anticipating that this type of thing would often happen in a rails environment which would inherit from AR, but I can't see anything wrong with your line of thinking. That came out of @jrhorn424's head, so let's wait for him to respond.

**Comment by jrhorn424** [comment]
How'd you know Chris? `git blame`? ;)

**Comment by jrhorn424** [comment]
This was from back when class methods came after Rails.

The point is to say "yo! this might not seem important, but we use class methods all the time". I'm not sure we lose a lot by deleting it, but I err on the side of clarifying the language to say ("soon you will see" or "in the context of Rails the following is common". They don't have to see any concrete implementations. Just understand the contract of the code example code in that section of the read me (call this method on the class with these arguments, get this back).

**Comment by payne-chris-r** [comment]
I like @jrhorn424 's suggestion (and yes, `git blame` 🤓 ), use it as a "preview" in a way.
